// <auto-generated />
using System;
using DoAnCuoiKy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnCuoiKy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204045310_deleteDeviceType")]
    partial class deleteDeviceType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookAuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserSearchHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("int");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookAuthorId");

                    b.HasIndex("BookChapterId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasFilter("[Title] IS NOT NULL");

                    b.HasIndex("UserSearchHistoryId");

                    b.ToTable("books");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookAuthor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("bookAuthors");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("CartStatus")
                        .HasMaxLength(20)
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CartStatus")
                        .HasDatabaseName("IX_BookCarts_UserId_Status");

                    b.ToTable("bookCarts");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CartId");

                    b.ToTable("bookCartItems");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("bookCategories");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TitleChapter")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TitleChapter")
                        .IsUnique()
                        .HasFilter("[TitleChapter] IS NOT NULL");

                    b.ToTable("bookChapters");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PublicIdFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PublicIdImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("bookFileType")
                        .HasMaxLength(20)
                        .HasColumnType("tinyint");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("bookFiles");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("BookStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ShelfSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ShelfSectionId");

                    b.ToTable("bookItems");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookPickupSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredPickupDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPickedUp")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledPickupDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowingId")
                        .IsUnique();

                    b.ToTable("bookPickupSchedules");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("usersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookItemId");

                    b.HasIndex("usersId");

                    b.ToTable("bookReservations");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Borrowing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("BorrowingStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LibrarianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isReminded")
                        .HasColumnType("bit");

                    b.Property<bool>("isScheduled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LibrarianId");

                    b.ToTable("borrowings");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BorrowingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BorrowingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFined")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("bookStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookItemId");

                    b.HasIndex("BorrowingId");

                    b.ToTable("borrowingDetails");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Fine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BorrowingDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DaysLate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FineRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LibrarianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("fineReason")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BorrowingDetailId");

                    b.HasIndex("LibrarianId");

                    b.ToTable("fines");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.BookExportTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowingDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("ExportReason")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowingDetailId");

                    b.ToTable("bookExportTransactions");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.BookImportTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("bookImportTransactions");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.BookShelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookShelfName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("NumberOfShelves")
                        .HasColumnType("int");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("bookShelves");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FloorName")
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("floors");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FloorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxBookShelfCapity")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Shelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookshelfId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("NumberOfSections")
                        .HasColumnType("int");

                    b.Property<string>("ShelfName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookshelfId");

                    b.ToTable("shelves");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.ShelfSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SectionName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ShelfId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShelfId");

                    b.ToTable("shelfSections");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BorrowAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BorrowingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("PaymentType")
                        .HasColumnType("tinyint");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VnpResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VnpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vnpBankCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowingId")
                        .IsUnique()
                        .HasFilter("[BorrowingId] IS NOT NULL");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PublisherName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherName")
                        .IsUnique()
                        .HasFilter("[PublisherName] IS NOT NULL");

                    b.ToTable("publishers");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.Notification.NotificationToUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("NotificationType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowingId");

                    b.HasIndex("UserId");

                    b.ToTable("notificationToUsers");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.BookRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClicked")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("RecommendationType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CreateDate")
                        .HasDatabaseName("IX_BookRecommendation_Date");

                    b.HasIndex("UserId", "CreateDate")
                        .HasDatabaseName("IX_BookRecommendation_User_Date");

                    b.HasIndex("UserId", "Score")
                        .HasDatabaseName("IX_BookRecommendation_User_Score");

                    b.ToTable("bookRecommendations");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.UserBookInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("InteractionType")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_UserBookInteraction_BookId");

                    b.HasIndex("CreateDate")
                        .HasDatabaseName("IX_UserBookInteraction_Date");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserBookInteraction_UserId");

                    b.HasIndex("UserId", "InteractionType")
                        .HasDatabaseName("IX_UserBookInteraction_User_Type");

                    b.HasIndex("BookId", "InteractionType", "CreateDate")
                        .HasDatabaseName("IX_UserBookInteraction_Book_Type_Date");

                    b.ToTable("userBookInteractions");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.UserCategoryPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BorrowCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastInteraction")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PreferenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ReadingMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserCategoryPreference_User_Category");

                    b.HasIndex("UserId", "PreferenceScore")
                        .HasDatabaseName("IX_UserCategoryPreference_User_Score");

                    b.ToTable("userCategoryPreferences");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.UserReadingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LastPageNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("ReadingProgress")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_UserReadingSession_BookId");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_UserReadingSession_StartTime");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserReadingSession_UserId");

                    b.HasIndex("UserId", "BookId", "StartTime")
                        .HasDatabaseName("IX_UserReadingSession_Composite");

                    b.ToTable("userReadingSessions");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.UserSearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchKeyword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SearchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateDate")
                        .HasDatabaseName("IX_UserSearchHistory_SearchedAt");

                    b.HasIndex("SearchKeyword")
                        .HasDatabaseName("IX_UserSearchHistory_Keyword");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserSearchHistory_UserId");

                    b.HasIndex("UserId", "CreateDate")
                        .HasDatabaseName("IX_UserSearchHistory_User_Date");

                    b.ToTable("userSearchHistories");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isValidate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("librarians");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.Usermanage.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.Usermanage.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.BookAuthor", "BookAuthor")
                        .WithMany("books")
                        .HasForeignKey("BookAuthorId");

                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.BookChapter", "BookChapter")
                        .WithMany("books")
                        .HasForeignKey("BookChapterId");

                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCategory", "Category")
                        .WithMany("books")
                        .HasForeignKey("CategoryId");

                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId");

                    b.HasOne("DoAnCuoiKy.Model.Entities.UserBehavior.UserSearchHistory", null)
                        .WithMany("Books")
                        .HasForeignKey("UserSearchHistoryId");

                    b.Navigation("BookAuthor");

                    b.Navigation("BookChapter");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCart", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", "Librarian")
                        .WithMany("bookCarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCartItem", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", "Book")
                        .WithMany("BookCartItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCart", "BookCart")
                        .WithMany("BookCartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookCart");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookFile", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", "book")
                        .WithMany("bookFiles")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("book");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookItem", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", "Book")
                        .WithMany("bookItems")
                        .HasForeignKey("BookId");

                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.ShelfSection", "ShelfSection")
                        .WithMany("BookItems")
                        .HasForeignKey("ShelfSectionId");

                    b.Navigation("Book");

                    b.Navigation("ShelfSection");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookPickupSchedule", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Borrowing", "borrowing")
                        .WithOne("BookPickupSchedule")
                        .HasForeignKey("DoAnCuoiKy.Model.Entities.InformationLibrary.BookPickupSchedule", "BorrowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("borrowing");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookReservation", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.BookItem", "BookItem")
                        .WithMany("BookReservations")
                        .HasForeignKey("BookItemId");

                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Users", "users")
                        .WithMany()
                        .HasForeignKey("usersId");

                    b.Navigation("BookItem");

                    b.Navigation("users");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Borrowing", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", "Librarian")
                        .WithMany("borrowings")
                        .HasForeignKey("LibrarianId");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BorrowingDetail", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.BookItem", "bookItem")
                        .WithMany("borrowingDetails")
                        .HasForeignKey("BookItemId");

                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Borrowing", "borrowing")
                        .WithMany("borrowingDetails")
                        .HasForeignKey("BorrowingId");

                    b.Navigation("bookItem");

                    b.Navigation("borrowing");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Fine", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.BorrowingDetail", "borrowingDetail")
                        .WithMany("fines")
                        .HasForeignKey("BorrowingDetailId");

                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", "librarian")
                        .WithMany("fines")
                        .HasForeignKey("LibrarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("borrowingDetail");

                    b.Navigation("librarian");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.BookExportTransaction", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.BorrowingDetail", "BorrowingDetail")
                        .WithMany("bookExportTransactions")
                        .HasForeignKey("BorrowingDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorrowingDetail");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.BookImportTransaction", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", "book")
                        .WithMany("ImportTransactions")
                        .HasForeignKey("BookId");

                    b.Navigation("book");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.BookShelf", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Room", "Room")
                        .WithMany("BookShelves")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Room", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Shelf", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.BookShelf", "Bookshelf")
                        .WithMany("Shelves")
                        .HasForeignKey("BookshelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookshelf");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.ShelfSection", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Shelf", "Shelf")
                        .WithMany("Sections")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Payment", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Borrowing", "Borrowing")
                        .WithOne("Payment")
                        .HasForeignKey("DoAnCuoiKy.Model.Entities.InformationLibrary.Payment", "BorrowingId");

                    b.Navigation("Borrowing");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.Notification.NotificationToUser", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Borrowing", "borrowing")
                        .WithMany("notificationToUsers")
                        .HasForeignKey("BorrowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", "librarian")
                        .WithMany("notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("borrowing");

                    b.Navigation("librarian");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.BookRecommendation", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", "Book")
                        .WithMany("bookRecommendations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", "Librarian")
                        .WithMany("bookRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.UserBookInteraction", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", "Book")
                        .WithMany("userBookInteractions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", "Librarian")
                        .WithMany("userBookInteractions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.UserCategoryPreference", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCategory", "BookCategory")
                        .WithMany("userCategoryPreferences")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", "Librarian")
                        .WithMany("categoryPreference")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCategory");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.UserReadingSession", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", "Book")
                        .WithMany("userReadingSessions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", "Librarian")
                        .WithMany("userReadingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.UserSearchHistory", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", "Librarian")
                        .WithMany("userSearchHistories")
                        .HasForeignKey("UserId");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Role", "Role")
                        .WithMany("librarians")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.Usermanage.Users", b =>
                {
                    b.HasOne("DoAnCuoiKy.Model.Entities.Usermanage.Role", "Role")
                        .WithMany("users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Book", b =>
                {
                    b.Navigation("BookCartItems");

                    b.Navigation("ImportTransactions");

                    b.Navigation("bookFiles");

                    b.Navigation("bookItems");

                    b.Navigation("bookRecommendations");

                    b.Navigation("userBookInteractions");

                    b.Navigation("userReadingSessions");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookAuthor", b =>
                {
                    b.Navigation("books");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCart", b =>
                {
                    b.Navigation("BookCartItems");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookCategory", b =>
                {
                    b.Navigation("books");

                    b.Navigation("userCategoryPreferences");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookChapter", b =>
                {
                    b.Navigation("books");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BookItem", b =>
                {
                    b.Navigation("BookReservations");

                    b.Navigation("borrowingDetails");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Borrowing", b =>
                {
                    b.Navigation("BookPickupSchedule");

                    b.Navigation("Payment");

                    b.Navigation("borrowingDetails");

                    b.Navigation("notificationToUsers");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.BorrowingDetail", b =>
                {
                    b.Navigation("bookExportTransactions");

                    b.Navigation("fines");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.BookShelf", b =>
                {
                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Room", b =>
                {
                    b.Navigation("BookShelves");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.Shelf", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Kho.ShelfSection", b =>
                {
                    b.Navigation("BookItems");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.InformationLibrary.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.UserBehavior.UserSearchHistory", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.Usermanage.Librarian", b =>
                {
                    b.Navigation("bookCarts");

                    b.Navigation("bookRecommendations");

                    b.Navigation("borrowings");

                    b.Navigation("categoryPreference");

                    b.Navigation("fines");

                    b.Navigation("notifications");

                    b.Navigation("userBookInteractions");

                    b.Navigation("userReadingSessions");

                    b.Navigation("userSearchHistories");
                });

            modelBuilder.Entity("DoAnCuoiKy.Model.Entities.Usermanage.Role", b =>
                {
                    b.Navigation("librarians");

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
